---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: adamantos
description: AdamantOS – Ein unzerstörbares, wartungsfreies Bluefin-Derivat für den deutschen Markt.

base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - wget
      - curl
      - unzip
      - rsync
      - p7zip
      - p7zip-plugins
      - dkms
      - linux-firmware
      - intel-microcode
      - amd64-microcode
      - tlp
      - tlp-rdw
      - langpacks-de
      - lame
      - wavpack
      - flac
      - vorbis-tools
      - ffmpeg
      - kid3-cli
      - systemd-zram-generator
      - timeshift
      - hardinfo2
      - gnome-tweaks
      - gnome-contacts
      - gnome-maps
      - gnome-weather
      - nautilus-admin
      - nautilus-share
      - gnome-sushi
      - ffmpegthumbnailer
      - gtkhash
      - nautilus-image-converter

  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://flathub.org/repo/flathub.flatpakrepo
      install:
        - org.gnome.Showtime
        - org.gnome.Lollypop
        - de.haeckerfelix.Shortwave
        - org.gtk.Gtk3theme.Adwaita-dark
        - com.mattjakeman.ExtensionManager
        - org.localsend.localsend_app
        - com.bitwarden.desktop
        - com.rustdesk.RustDesk
        - org.remmina.Remmina
        - be.alexandervanhee.gradia
        - net.codelogistics.webapps
        - com.github.unrud.VideoDownloader
        - com.valvesoftware.Steam
        - com.heroicgameslauncher.hgl
        - net.davidotek.pupgui2
        - com.github.Matoking.protontricks
        - io.github.Faugus.faugus-launcher
        - com.benjamimgois.goverlay

  - type: bling
    install:
      - dconf-update-service

  - type: script
    scripts:
      - post-install.sh
