name: Build AdamantOS ISO

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          image-name: 'adamantos'
          image-repo: 'ghcr.io/evilware666-guideos-dev'
          image-tag: 'latest'
          version: '43' # <-- WICHTIG: Die Fedora-Version deines Basis-Images
          variant: 'Silverblue'
          iso-name: 'adamantos-latest.iso'

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
            ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
